#!/usr/bin/env python

import sys, re

file_path = sys.argv[1]

with open(file_path, "r+") as f:
    commit_msg_lines = f.readlines()
    num_chars = 0
    for i in range(0,len(commit_msg_lines)):
        line = commit_msg_lines[i]
        if i == 0:
            validate_prefix(line) 
        if len(line) > 70: 
            sys.exit(1)
        num_chars += len(line)

    if num_chars > 76: 
        sys.exit(1)
    
def validate_prefix(msg):
    prefix = re.match("^[A-Za-z_0-9]+:", msg)
    prefix_fixes = re.match("^([A-Za-z_0-9]+) (#[0-9]+):", msg)
    if (prefix is None and prefix_fixes is None): 
        sys.exit(1)

    if prefix_fixes and prefix_fixes.group(1).lower() != "fixes": 
            sys.exit(1)
        #TODO: optionally fix it if they forgot the '#' via elif 
